---
title: "Interactive Graph Examples"
author: "Minnie Ringland"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, we'll practice creating some interactive graphs and tables using builti-in datasets in R packages.

- Interactive plots: {plotly}
- Interactive tables: {DT}




```{r, include = FALSE}
#Attach packages

library(tidyverse)
library(plotly)
library(DT)

```


### A. Interactive graph of iris dimensions

Using Edgar Anderson's famous 'iris' dataset

```{r, echo = FALSE}

iris_graph <- ggplot(data = iris, aes(x = Petal.Width,
                                      y = Petal.Length)) +
  geom_point(aes(size = Sepal.Width,
                 color = Species),
             alpha = 0.5) +
  theme_minimal() +
  labs(x = "Petal Width (cm)",
      y = "Petal Length (cm)",
      title = "My Iris Graph")

# iris_graph

# Once you have a graph stored, you should always make sure the static version works first before making it interactive/reactive.


# Now we can use plotly to make this graph interactive
 ggplotly(iris_graph)



```







